### ISSUE TITLE
aponia | rTensor

### ISSUE THREAD

**Issue by rTensor** [rTensor/rTensor.github.io#14]
https://blog.rtensor.net/2019/06/10/aponia/ 

 关于 (3) 的解释  “怎么办，我好喜欢您啊(” $\to$ “嗯?不是听听就好了吗” $\to$ 所以是只是说说吗 $\to$ 大概也就是听听了 $\to$ 届不到 (1)  都讨论过奇怪的话题 &amp; 被寄过奇怪的东西  $\to$  以为能届到 (2)  想届到 (3)  (1)–(3) -&gt; 发作

**Comment by guxiaoshahua** [comment]
sb

**Comment by guxiaoshahua** [comment]
赶紧删了
